webtalk_init -webtalk_dir /home/yangz0e/Desktop/top-k-streaming/top-k-streaming.sim/sim_1/behav/xsim/xsim.dir/testbench_toplevel_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 29 16:38:23 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3286242" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211887999_1777552194_210720986_228" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0da8e86b-1e4c-413e-a31b-ef6b0a1793a8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "90c15a37356346fab2a6c808b3a209c1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "202" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen Threadripper PRO 3975WX 32-Cores" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2198.721 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "540.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.41_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "131832_KB" -context "xsim\\usage"
webtalk_transmit -clientid 323502143 -regid "211887999_1777552194_210720986_228" -xml /home/yangz0e/Desktop/top-k-streaming/top-k-streaming.sim/sim_1/behav/xsim/xsim.dir/testbench_toplevel_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/yangz0e/Desktop/top-k-streaming/top-k-streaming.sim/sim_1/behav/xsim/xsim.dir/testbench_toplevel_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/yangz0e/Desktop/top-k-streaming/top-k-streaming.sim/sim_1/behav/xsim/xsim.dir/testbench_toplevel_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
