#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1.1 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Wed Mar 29 16:38:23 +03 2023
# SW Build 3286242 on Wed Jul 28 13:09:46 MDT 2021
#
# IP Build 3279568 on Wed Jul 28 16:48:48 MDT 2021
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -prj testbench_toplevel_vlog.prj"
xvlog --incr --relax -prj testbench_toplevel_vlog.prj 2>&1 | tee compile.log

# compile VHDL design sources
echo "xvhdl --incr --relax -prj testbench_toplevel_vhdl.prj"
xvhdl --incr --relax -prj testbench_toplevel_vhdl.prj 2>&1 | tee -a compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
